# Generated by Django 4.0.5 on 2023-03-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
