# Generated by Django 4.0.5 on 2023-04-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0003_innovator_uploads_category1_and_more'),
        ('user', '0003_alter_register_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('iu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.innovator_uploads')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register')),
            ],
        ),
    ]
