# Generated by Django 4.0.5 on 2023-04-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_order_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_show',
            name='payment',
        ),
    ]
