# Generated by Django 4.1.2 on 2024-08-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_order_show_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aboutus',
            new_name='about_us',
        ),
        migrations.RenameModel(
            old_name='subcategory',
            new_name='sub_category',
        ),
        migrations.RenameModel(
            old_name='userupload',
            new_name='user_upload',
        ),
    ]
