# Generated by Django 4.0.5 on 2023-03-26 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='register1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('phoneno', models.IntegerField()),
                ('email1', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.category1')),
            ],
        ),
        migrations.CreateModel(
            name='innovator_uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=50)),
                ('idea_title', models.CharField(max_length=50)),
                ('idea_image', models.ImageField(upload_to='images/')),
                ('idea_description', models.TextField()),
                ('idea_document', models.FileField(upload_to='documents/')),
                ('date', models.DateField()),
                ('urls', models.URLField(max_length=300)),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.category1')),
                ('innovator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.register1')),
                ('subcategory1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovator.subcategory1')),
            ],
        ),
    ]
