# Generated by Django 4.0.5 on 2023-03-27 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0002_remove_innovator_uploads_category1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovator_uploads',
            name='category1',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='innovator.category1'),
        ),
        migrations.AddField(
            model_name='innovator_uploads',
            name='subcategory1',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='innovator.subcategory1'),
        ),
    ]
