# Generated by Django 4.0.5 on 2023-04-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0003_innovator_uploads_category1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovator_uploads',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
