# Generated by Django 4.0.5 on 2023-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0004_innovator_uploads_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovator_uploads',
            name='price',
            field=models.IntegerField(max_length=4),
        ),
    ]
