# Generated by Django 4.1.2 on 2024-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0005_alter_innovator_uploads_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category1',
            new_name='category_innovator',
        ),
        migrations.RenameModel(
            old_name='register1',
            new_name='register_innovator',
        ),
        migrations.RenameModel(
            old_name='subcategory1',
            new_name='sub_category_innovator',
        ),
        migrations.RenameField(
            model_name='innovator_uploads',
            old_name='category1',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='innovator_uploads',
            old_name='subcategory1',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='register_innovator',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='register_innovator',
            old_name='phoneno',
            new_name='phone_no',
        ),
        migrations.AlterField(
            model_name='innovator_uploads',
            name='price',
            field=models.IntegerField(),
        ),
    ]
