# Generated by Django 4.1.2 on 2024-08-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0006_rename_category1_category_innovator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_innovator',
            old_name='email1',
            new_name='email',
        ),
    ]
