# Generated by Django 4.1.2 on 2024-10-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0007_rename_email1_register_innovator_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovator_uploads',
            name='date',
        ),
    ]
